# Generated by Django 5.1.7 on 2025-09-08 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SampleModel',
        ),
    ]
